config/routes.rb
MusicApp::Application.routes.draw do
  resources :songs, only: :index

  root 'songs#index'

  

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :songs
  belongs_to :artist
  scope :sorted, lambda { order("albums.name ASC") }
  validates :name, uniqueness: true
  validates :name, presence: true
    
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :albums
  has_many :songs, :through => :albums
  scope :sorted, lambda { order("artist.name ASC") }
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/search_engine.rb
class SearchEngine

  attr_reader :song, :album, :artist
  
  def initialize(params)
  	params ||= {}
    @song = params[:song]
	@artist = params[:artist]
	@album = params[:album]
	    puts "IN SEARCH params = "#{@params.inspect}"

  end
  
  def song_search()
    puts "IN SONG SEARCH artist = "#{@artist}"
    s = Song
    s = s.where('songs.name like ?', "#{@song}%") if @song.present?      
=begin   
    used if not using like
    s = s.where(name: @song) if @song.present?
    s = s.includes(:album).where(albums: { name: @album }) if @album.present?
    s = s.joins(:artist).includes(:artist).where(artists: { name: @artist }) if @artist.present?
=end
    s = s.includes(:album).where('albums.name like ?', "#{@album}%" ).references(:albums) if @album.present?
    s = s.joins(:artist).includes(:artist).where('artists.name like ?', "#{@artist}%").references(:artist) if @artist.present?
    
    s.kind_of?(ActiveRecord::Relation)  ?   s.sorted   : nil

  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_one :artist, :through => :album
  belongs_to :album
  validates :name, uniqueness: true
  validates :name, presence: true
  scope :sorted, lambda { order("songs.name ASC") }
  def albums_name
	self.album.name
  end
  
  def artists_name
	self.artist.name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
 before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @search = SearchEngine.new(params[:search])
	@songs = @search.song_search()
    if @songs and @songs.size == 0
        flash[:notice] = "No Songs match the Crtieria" 
    else 
        flash[:notice] = nil
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render action: 'show', status: :created, location: @song }
      else
        format.html { render action: 'new' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<!--
  %= javascript_include_tag "application", "data-turbolinks-track" => true 
-->
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">    
</head>
<body>
    <% if notice %>
        <p id="notice"><%= notice %></p>
    <% end%>
<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/_song.html.erb
     <tr class="<%= cycle('list_line_odd', 'list_line_even') %>"</t>
        <td><%= song.name %></td>
        <td><%= song.albums_name %></td>
        <td><%= song.artists_name %></td>
     </tr>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Songs</h1>

<div>
	<table  id="search_table">
		<thead>
			<tr>
				<th>Song Name </th>
				<th>Albums Name</th>
				<th>Artist Name</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<%= form_tag songs_path, method: :get do %>
				<tr>
					<td><%= text_field_tag 'search[song]', @search.song %></td>
					<td><%= text_field_tag 'search[album]', @search.album %></td>
					<td><%= text_field_tag 'search[artist]', @search.artist %></td>
                    <td><%=submit_tag "Search", id: 'search_button' %></td>
				<tr>
			<%end%>
		</tbody>
	</table>
</div>
<div>
<table id = "songs">
  <thead>
    <tr>
      <th>Song</th>
      <th>Album</th>
      <th>Artist</th>
    </tr>
  </thead>

  <tbody>
      <%= render(@songs) if @songs%>
  </tbody>
</table>
</div>
<br>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>